### ISSUE TITLE
Option selection breaks when there are more options than lines in terminal window

### ISSUE THREAD

**Issue by Dandry** [IngoHeimbach/simple-term-menu#3]
Hello, first of all I would like to thank the author for the amazing work that's been done in this project. 

I have noticed a tiny anomaly in how the module works when there are more options in a menu than lines available in terminal window. Then, the cursor and the highlighted option "desynchronize" and also some of the options are gone. Please look at the following example:
Example code from [Readme.md](https://github.com/IngoHeimbach/simple-term-menu/blob/master/README.md), here are the menu options:
```
 main_menu_items = [
      "Item 1",
      "Item 2",
      "Item 3",
      "Item 4",
      "Item 5",
      "Item 6",
      "Item 7",
      "Item 8",
      "Item 9",
      "Item 10",
      "Item 11",
      "Item 12",
      "Item 13",
      "Item 14",
      "Item 15",
      "Item 16",
      "Item 17",
      "Item 18",
      "Item 19",
      "Item 20",
      "Item 21",
      "Item 22",
      "Item 23",
      "Item 24",
      "Item 25",
      "Quit"]
```
Launching the script in a terminal window with less lines than the options above, I get the following outcome:
![image](https://user-images.githubusercontent.com/19386340/81570031-55196700-93a0-11ea-8e85-518c9249db6c.png)
When I press the up arrow button on my keyboard to see previous options, terminal output presents empty lines:
![image](https://user-images.githubusercontent.com/19386340/81570104-6cf0eb00-93a0-11ea-92b9-ff3316a0cdfb.png)
I am able to keep pushing the up arrow button and after a dozen blank lines I reach the same thing as presented on the first screenshot, but I am unable to see first 18 options. When I keep smashing up and down arrow keys I was able to see a flash of other options, but just for a fraction of a second.
Thank you for your help.

**Comment by IngoHeimbach** [comment]
Hey,
thanks for using `simple-term-menu`. It's nice that this project is useful for you. :smile: 
I can confirm the bug. I will look into this.

**Comment by IngoHeimbach** [comment]
The bug is fixed in commit 594f70b975723ac11916eb04da197dccd9d6f4ab and in the bug fix release [v0.4.6](https://pypi.org/project/simple-term-menu/0.4.6/).

**Comment by IngoHeimbach** [comment]
If the menu has more entries than available terminal lines, the shown viewport scrolls automatically if necessary. The new release also truncates menu entries which are too long and handles terminal resizing.

**Comment by Dandry** [comment]
Hi @IngoHeimbach, I confirm that the issue has been fixed in the latest release. Thank you so much for your quick response and the fix, that was impressive. I hope one day I will be able contribute to your project (once I get to know Python more, because right now I am using your module in the first python script I have ever written :)). 
Thank you again for this project and all your hard work.
Best regards!
